apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - args:
    - server_pod
    image: server:v1
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
